version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rewards_backend_development
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - BUNDLE_WITHOUT=""
      - BUNDLE_DEPLOYMENT=""
      - DATABASE_URL=mysql2://root:root@db/rewards_backend_development
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
  bundle_cache: