default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: db

development:
  <<: *default
  database: rewards_backend_development

test:
  <<: *default
  database: rewards_backend_test

production:
  primary: &primary_production
    <<: *default
    database: rewards_backend_production
    username: rewards_backend
    password: <%= ENV["REWARDS_BACKEND_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rewards_backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rewards_backend_production_queue
    migrations_paths: db/queue_migrate
